name: Checks
on: [push]
jobs:
  Test:
    runs-on: windows-latest
    steps:
      - uses: lukka/get-cmake@latest
      
      - name: Run CMake consuming CMakePresets.json and vcpkg.json by mean of vcpkg.
        uses: lukka/run-cmake@v10
        with: 
          cmakeListsTxtPath: "$RUNNER_WORKSPACE\CMakeLists.txt"
