name: Run clang-format Linter

on: [push, pull_request]

jobs:
  Lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.14
      with:
        style: llvm
        source: '.'
        exclude: '**/vendor'
        extensions: 'cpp,hpp'
        clangFormatVersion: 14
        inplace: True
    - uses: EndBug/add-and-commit@v4
      with:
        message: 'Committing clang-format changes'
